### ISSUE TITLE
$tokenizer->tokens вырезает отдельно стоящие "0"

### ISSUE THREAD

**Issue by kmike** [ksurent/Lingua--RU--OpenCorpora--Tokenizer#1]
Привет! Играюсь с токенизацией; запустил Lingua::RU::OpenCorpora::Tokenizer и, вроде, нашел ошибку: метод tokenize вырезает отдельно стоящие символы "0". 

В перле полный профан; соорудил такой скрипт:

```
#!/usr/bin/env perl
use utf8;
use Lingua::RU::OpenCorpora::Tokenizer;
use Encode;

my $tokenizer = my $tokenizer = Lingua::RU::OpenCorpora::Tokenizer->new;

$|++;
while(<>){
    my $text = Encode::decode("utf8", $_);
    my $tokens = $tokenizer->tokens($text, {'threshold' => 0.5});

    for(my $i=0; $i<@{$tokens}; $i++) {
        print Encode::encode("utf8", $tokens->[$i]), "\n";
    }
    print "--END\n";
}
```

Если там вбить, например, "от 0 до 2", то напечатает

```
от
до
2
--END
```

Код - последний с гитхаба. Кстати, почему 0.07 на CPAN нет?) 

Возможно, это я что-то напортачил с установкой - сначала ставил с CPAN 0.06, потом поверх с гитхаба уже через make.

**Comment by kmike** [comment]
В `0.Привет` тоже 0 пропадает - токенизатор бьет на точку и "Привет".

**Comment by ksurent** [comment]
Да, похоже на баг. Спасибо за репорт.
С большой вероятностью уже знаю в чем проблема. Починю в ближайшее время.

На CPAN нет последней версии потому, что в ней затаился баг из–за которого получается регрессия в F1 (не очень большая, но заметная). Времени пофиксить пока не хватает.
