### ISSUE TITLE
Токенизатор пару "<точка> <цифра>" считает одним токеном и не разбивает по пробелу

### ISSUE THREAD

**Issue by kmike** [ksurent/Lingua--RU--OpenCorpora--Tokenizer#2]
Запустил его на всем корпусе; в результатах токенизации очень много подобных ошибок:

```
валюте|Российской|Федерации|.|6|.|Неисполнение|обязанности               . 6
предусмотренных|настоящим|Кодексом|.|7|.|Поручение|на                    . 7
об|уточнении|платежа|.|8|.|Правила|,                                     . 8
```

(". 6" - это отдельный токен, с пробелом).

Предположение - токенизатор тренировали на тексте, уже разбитом на предложения.

**Comment by ksurent** [comment]
А можно пару примеров с полным исходным текстом?

**Comment by kmike** [comment]
Там в исходниках несколько модулей на питоне (с использованием ipython, numpy, pymorphy2, scikit-learn), общение с перловым скриптом (из предыдущего тикета) через subprocess/пайпы и достаточно много всяких штук, прямого отношения к делу не имеющих - выложить несложно, запустить может быть нетривиально :) 

Если по сути, то перловый скрипт (из предыдущего тикета) натравил на полный корпус OpenCorpora (предложения соединены пробелами, текст предложений взят из тега source в XML, документы не объединялись и разбирались отдельно) и сравнил результаты токенизации с теми, что выдал скрипт (через питоний difflib). Результат: https://dl.dropbox.com/u/21197464/perl.txt (на первую строку можно не обращать внимание, там мусор). Каждая строка - это тройка `<действие> <"золотое" разбиение> <то, с чем скрипт не согласен>`. "Золотое" разбиение - с контекстом +-3 токена, символ | показывает границы токенов; в "том, с чем перловый скрипт не согласен" токены тоже разделены |, но все уже без контекста. 

Например, чтоб повторить первый пример из тикета, нужно запустить метод tokenize на тексте "валюте Российской Федерации. 6. Неисполнение обязанности" - точка, пробел и цифра 6 будут объединены в 1 токен.

**Comment by ksurent** [comment]
Похоже баг был в обучалке. Откатил данные.
Я прогнал тесты на паре десятков случайных (из тех, у которых были проблемы с ". <цифры>") предложений из perl.txt, стало гораздо лучше.
Если у тебя уже есть скрипт, который прогоняет по всему корпусу, мог бы еще и им проверить, пожалуйста?

**Comment by kmike** [comment]
Ага, сейчас прогоню и новый perl.txt выложу.

**Comment by kmike** [comment]
С новыми данными еще один баг исчез, похожий на #1, но который я тогда не заметил (токенизатор вырезал юникодное тире "—"): 

```
the|17|th|—|20-th|Centuries|.|A   
```

Результат по precision/recall/F1 для обновленного токенизатора (как в статье, без учета пробелов):
Score(precision=0.99556763602106535, recall=0.9793636405070214, F1=0.98739916266721128, support=197467, errors=4936)

Для старого посчитать не удавалось, т.к. длины результатов не совпадали (из-за #1 и вырезания "—").

diff с ошибками пока считается (это довольно медленно).

**Comment by kmike** [comment]
Кстати, метрика F1 на основе количества ошибок в границах мне кажется далеко не идеальной для оценки токенизатора; я бы сильно не волновался о регрессиях в этой метрике, а смотрел больше на ошибки, которые токенизатор делает. 

С учетом того, что в исходном корпусе немало ошибок токенизации (см. https://docs.google.com/spreadsheet/ccc?key=0As9XSeRgdNihdHYxaUVYNkl5NTA3dE9CaThtaENYdlE ) , совсем большое значение F1 означает, что токенизатор делает те же ошибки - не может их выявить в корпусе; кроме того, оптимизация F1 может приводить к "половинчатым" решениям (которые, как мне кажется, хуже "полных") - и приводит, например

`replace По|данным|на|2:50|был|создан|оперативный                                         2|:50`

Пример: пусть у нас есть текст "в каком-то", и "золотое" разбиение для него `в/каком/-/то`. Тогда F1 будет лучше для разбиения `в/каком-/то`, чем для `в/каком-то`, если F1 считать по "разбито-не разбито" для каждого промежутка между двумя буквами. 

Но метрику лучше F1 я пока предложить не могу; возможно, подойдет какая-нибудь немного поправленная стандартная метрика для оценки сегментации (Pk, windowdiff и тд) - чтоб "near-misses" пенализировались (может русское слово есть получше?) с той же силой, что и другие промахи; можно еще F1 считать для правильно выделенных токенов (или для пар границ), а не для отдельных границ, чтоб не поощрять частичное разбиение. Но я это все не пробовал и не реализовывал еще, так, идеи.

**Comment by kmike** [comment]
Новый файл с ошибками: https://dl.dropbox.com/u/21197464/perl2.txt - 2796 расхождений (= строк в диффе) вместо 4387, но полно как раз "половинчатых" ошибок с токенами "поймать-", "ящика-" и т.д. 

С учетом того, что токенизатор не спрашивает Яндекс.Словарь о том, нужно ли делить токен по дефису, а при ручной токенизации это было критерием деления, такие "половинчатые" разбиения могут быть для токенизатора лучшей стратегией, чтоб улучшить F1 :)

Упс, кстати, баг с длинным дефисом остался.

**Comment by ksurent** [comment]
На данный момент (по крайней мере, в моем понимании) перловый токенизатор является портом оригинальной реализации (lib_tokenize.php и collect_data.pl в репозитории ОпенКорпоры). Могу отдельно объяснить почему это так. Это накладывает некоторые ограничения на то, что я могу и не могу делать в этой реализации.
В идеале, когда я наконец допилю обучалку, я попробую уговорить ребят из ОпенКорпоры заменить оригинальную реализацию на Lingua::RU::OpenCorpora::Tokenizer (т.к. она все равно на перле написана). Вот тогда можно будет начинать экспериментировать с метриками и прочим.

Что касается данного бага. Считаю, что он пофиксен. Тикет закрываю.
Теперь что касается остальных багов. Для них надо будет завести отдельные тикеты :)
