### ISSUE TITLE
совместимость с Python

### ISSUE THREAD

**Issue by anklowait** [ksurent/Lingua--RU--OpenCorpora--Tokenizer#3]
Добрый день, а есть ли способ использовать токенизатор с помощью python ?

**Comment by ksurent** [comment]
Привет. Конкретно этот модуль использовать из Python удобным образом не получится. Вижу два выхода:

1. Реализовать алгоритм из статьи на Python
1. Вызывать библиотеку через запуск внешнего Perl интерпретатора из Python

**Comment by anklowait** [comment]
Спасибо!
